import numpy as np
# x = np.array([[1,2],[3,4],[5]])
# w = np.array([[1,1,1],[1,1,1]])
# # print(np.dot(x,w))
x = np.random.rand(10,1)
w= np.random.rand(2,3)
# print(a*w2 == np.multiply(a,w2))
# print(np.matmul(x,w) == np.dot(x,w))
# print(np.dot(x,w))
# print(np.dot(x,w))
print(x)
print(x.shape)
a = np.sum(x, axis=0, keepdims=True)
print(a)
print(a.shape)
